# global settings
title: "SocketService"
description: "SocketService Microservice Framework"
url: https://socketservice.github.io

# build settings
exclude: ["index.md", "package.json", "node_modules"]
